[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
amm_program = "6vXqLyZ4U9e3d1M5Xn8atqdWdHqpyyUx2MQ3kZHC7X9e"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
